apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "maven-hello-world.fullname" . }}
  labels:
    {{- include "maven-hello-world.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "maven-hello-world.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
