# Name of the workflow
name: Maven Version Increment, Build, and Docker Push

# Trigger event (when to run the workflow)
on:
  push:
    branches: [ master ]

# Job definition (what to run in the workflow)
jobs:
  build:
    # Name of the job
    name: Increment version patch, Build with Maven, and Push Docker image
    
    # Runner environment (where to run the job)
    runs-on: ubuntu-latest
    
    # Steps of the job (how to run the job)
    steps:
      # Check out the repository
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this fetches all history for all branches and tags
      
      # Install Java
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Increment version and build with Maven
      - name: Increment version patch, Build with Maven, and Push Docker image
        run: |
          # Extract the current version from the latest tag
          current_version=$(git describe --tags --match "[0-9]*.[0-9]*.[0-9]*" --abbrev=0)
          
          # Use 'awk' to increment the patch version
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++; print}')
          
          # Build the Docker image with the new version
          docker build -t charmingsteve/maven-hello-world:$new_version --build-arg revision=$new_version .
          
          # Tag the Docker image as 'latest'
          docker tag charmingsteve/maven-hello-world:$new_version charmingsteve/maven-hello-world:latest
          
          # Push the Docker images to Docker Hub
          docker push charmingsteve/maven-hello-world:$new_version
          docker push charmingsteve/maven-hello-world:latest

      # Increment version in Git
      - name: Increment version patch and Build with Maven
        run: |
          # Extract the current version from the latest tag
          current_version=$(git describe --tags --match "[0-9]*.[0-9]*.[0-9]*" --abbrev=0)
          
          # Use 'awk' to increment the patch version
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++; print}')
          
          # Delete the old tag locally
          git tag -d $current_version
          
          # Delete the old tag from the remote repository
          git push origin :refs/tags/$current_version
          
          # Create a new tag with the new version
          git tag $new_version
          
          # Push the new tag to the remote repository
          git push --tags
